import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import { AppContextProvider } from "@/context/app";
import { AuthContextProvider } from "@/context/auth";
import { NavContextProvider } from "@/context/nav-context";
import ThemeCustomization from "@/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <AppContextProvider>
            <ThemeCustomization>
              <NavContextProvider>{children}</NavContextProvider>
            </ThemeCustomization>
          </AppContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
